import { EVERYDAY_SCENARIOS } from '../everydayScenarioExpansion';

export type ScenarioCategory =
  | 'travel' | 'work' | 'service' | 'health' | 'social' | 'education'
  | 'home' | 'finance' | 'technology' | 'negotiation' | 'emergency' | 'daily';

export type ScenarioRole = {
  id: string;
  titleFa: string;
  titleEn: string;
  perspective: string;
  goals: string[];
};

export type Scenario = {
  id: string;
  titleFa: string;
  titleEn: string;
  category: ScenarioCategory;
  level: 'A1' | 'A2' | 'B1' | 'B2' | 'C1';
  dialects: Array<'iraqi' | 'lebanese' | 'american'>;
  context: string;
  roles: [ScenarioRole, ScenarioRole];
  objective: string;
  constraints: string[];
  opening: string;
  turnPlan: string[];
  tags: string[];
};

const role = (id: string, titleFa: string, titleEn: string, perspective: string, goals: string[]): ScenarioRole => ({ id, titleFa, titleEn, perspective, goals });

export const SCENARIOS: Scenario[] = [
  { id:'travel-airport-checkin', titleFa:'پذیرش فرودگاه و مشکل بار', titleEn:'Airport check-in and baggage issue', category:'travel', level:'A2', dialects:['iraqi','lebanese','american'], context:'مسافر برای پرواز آماده می‌شود و وزن بار از حد مجاز بیشتر است.', roles:[role('traveler','مسافر','Traveler','می‌خواهد پرواز را از دست ندهد و هزینه اضافی را بفهمد.',['پرسیدن وزن مجاز','انتخاب پرداخت یا کم‌کردن بار']),role('agent','کارمند پذیرش','Check-in agent','باید مقررات را روشن کند و راه‌حل عملی بدهد.',['توضیح محدودیت','پیشنهاد گزینه‌های مجاز'])], objective:'مشکل بار را با پرسش، مذاکره و تأیید نهایی حل کنید.', constraints:['قیمت و مقررات را حدس نزن؛ اگر عددی لازم است از کاربر بپرس.','در پایان زمان و اقدام بعدی را تأیید کن.'], opening:'You arrive at the airport and the agent tells you your checked bag is overweight.', turnPlan:['سلام و معرفی مسئله','پرسیدن محدودیت و هزینه','ارائه یک راه‌حل جایگزین','بررسی امکان پرداخت یا جابه‌جایی وسایل','تأیید تصمیم','پایان مؤدبانه'], tags:['airport','travel','problem-solving'] },
  { id:'hotel-late-checkin', titleFa:'ورود دیرهنگام به هتل', titleEn:'Late hotel check-in', category:'travel', level:'A2', dialects:['iraqi','lebanese','american'], context:'مسافر دیر به هتل رسیده و می‌خواهد اتاق رزروشده را تحویل بگیرد.', roles:[role('guest','مهمان','Guest','رزرو دارد اما دیر رسیده و به ورود سریع نیاز دارد.',['تأیید رزرو','پرسیدن امکانات و زمان صبحانه']),role('reception','پذیرش هتل','Receptionist','باید هویت، رزرو و قوانین ورود را بررسی کند.',['تأیید اطلاعات','توضیح کلید و امکانات'])], objective:'رزرو را تأیید کنید و تمام اطلاعات ضروری شب اول را بگیرید.', constraints:['اطلاعات شخصی حساس واقعی وارد نکن.','اگر اطلاعات رزرو ناقص است سؤال روشن بپرس.'], opening:'It is late at night. You arrive at a hotel with a reservation under your name.', turnPlan:['سلام و اعلام رزرو','تأیید نام و تاریخ','پرسیدن درباره اتاق و کلید','پرسیدن صبحانه و خروج','تأیید نهایی'], tags:['hotel','check-in','travel'] },
  { id:'taxi-wrong-route', titleFa:'تاکسی و مسیر اشتباه', titleEn:'Taxi and wrong route', category:'travel', level:'B1', dialects:['iraqi','lebanese'], context:'مسافر احساس می‌کند مسیر انتخاب‌شده با مقصد توافق‌شده فرق دارد.', roles:[role('passenger','مسافر','Passenger','می‌خواهد محترمانه مسیر را بررسی کند و سریع به مقصد برسد.',['توضیح مقصد','درخواست بررسی مسیر']),role('driver','راننده تاکسی','Driver','باید مسیر و دلیل انتخاب آن را توضیح دهد.',['توضیح مسیر','ارائه راه جایگزین'])], objective:'بدون تنش درباره مسیر سؤال کنید و راه‌حل مشترک پیدا کنید.', constraints:['اتهام مستقیم نزن.','از عبارت‌های نرم برای مخالفت استفاده کن.'], opening:'The taxi is moving in a direction you did not expect. Ask the driver about the route.', turnPlan:['پرسش محترمانه','توضیح مقصد','شنیدن دلیل راننده','پیشنهاد مسیر','تأیید مقصد'], tags:['taxi','directions','polite-disagreement'] },
  { id:'restaurant-allergy', titleFa:'رستوران و حساسیت غذایی', titleEn:'Restaurant allergy request', category:'health', level:'B1', dialects:['iraqi','lebanese','american'], context:'مشتری باید درباره ماده غذایی حساسیت‌زا مطمئن شود.', roles:[role('customer','مشتری','Customer','باید قبل از سفارش از نبود ماده حساسیت‌زا مطمئن شود.',['پرسیدن مواد اولیه','درخواست تغییر غذا']),role('server','پیشخدمت','Server','باید سؤال را جدی بگیرد و اگر مطمئن نیست بررسی کند.',['بررسی آشپزخانه','پیشنهاد گزینه امن'])], objective:'سؤال دقیق بپرسید، اطمینان بگیرید و سفارش را نهایی کنید.', constraints:['در مورد خطر پزشکی اغراق نکن.','اگر اطلاعات کافی نیست، درخواست بررسی کن.'], opening:'Before ordering, tell the server that you have a food allergy and need to check the ingredients.', turnPlan:['اعلام حساسیت','پرسیدن مواد','درخواست بررسی','انتخاب گزینه','تأیید سفارش'], tags:['restaurant','allergy','health'] },
  { id:'pharmacy-common-cold', titleFa:'داروخانه و علائم سرماخوردگی', titleEn:'Pharmacy conversation', category:'health', level:'B1', dialects:['iraqi','lebanese','american'], context:'مشتری علائم معمولی دارد و درباره گزینه بدون نسخه سؤال می‌کند.', roles:[role('customer','مشتری','Customer','می‌خواهد علائم را دقیق توصیف کند و محدودیت‌های خود را بگوید.',['توصیف علائم','پرسیدن روش مصرف و هشدارها']),role('pharmacist','داروساز','Pharmacist','باید سؤال‌های ایمنی بپرسد و در صورت نیاز ارجاع دهد.',['پرسیدن مدت علائم','توضیح محدودیت‌های دارویی'])], objective:'علائم را واضح بیان کنید و اطلاعات ایمنی لازم را بگیرید.', constraints:['سن، بیماری یا داروی واقعی را وارد نکن؛ سناریو اطلاعات نمونه می‌سازد.','تشخیص قطعی پزشکی نده.'], opening:'You have mild cold symptoms and ask a pharmacist what over-the-counter options are available.', turnPlan:['شرح علائم','پرسیدن مدت و شدت','پرسیدن محدودیت‌ها','دریافت دستور کلی','تأیید زمان مراجعه به پزشک'], tags:['pharmacy','health','safety'] },
  { id:'doctor-appointment', titleFa:'گرفتن وقت پزشک', titleEn:'Booking a doctor appointment', category:'health', level:'A2', dialects:['iraqi','lebanese','american'], context:'بیمار برای یک مشکل غیر اورژانسی دنبال وقت مناسب است.', roles:[role('patient','بیمار','Patient','نیاز به وقت دارد و می‌خواهد زمان مناسب پیدا کند.',['شرح کوتاه دلیل مراجعه','انتخاب زمان']),role('scheduler','منشی درمانگاه','Scheduler','باید زمان‌های موجود و مقدمات مراجعه را توضیح دهد.',['پیشنهاد زمان','توضیح مدارک لازم'])], objective:'یک وقت مناسب بگیرید و مراحل بعدی را بفهمید.', constraints:['اطلاعات شناسایی واقعی وارد نکن.'], opening:'Call a clinic to book a non-emergency appointment.', turnPlan:['سلام و درخواست وقت','شرح کوتاه دلیل','انتخاب زمان','پرسیدن مدارک','تأیید قرار'], tags:['clinic','appointment','phone'] },
  { id:'job-interview', titleFa:'مصاحبه شغلی', titleEn:'Job interview', category:'work', level:'B2', dialects:['american','iraqi','lebanese'], context:'متقاضی برای یک موقعیت شغلی عمومی مصاحبه می‌شود.', roles:[role('candidate','متقاضی','Candidate','باید تجربه، مهارت و انگیزه خود را روشن بیان کند.',['معرفی حرفه‌ای','پاسخ به سؤال رفتاری']),role('manager','مصاحبه‌کننده','Hiring manager','می‌خواهد شایستگی و تناسب نقش را ارزیابی کند.',['پرسیدن سؤال رفتاری','درخواست مثال مشخص'])], objective:'در مصاحبه طبیعی پاسخ دهید و برای ادعاهای خود مثال بدهید.', constraints:['رزومه ساختگی به‌عنوان واقعیت ارائه نکن.','پاسخ‌ها باید کوتاه، مشخص و قابل پیگیری باشند.'], opening:'You are interviewing for a role that requires communication, reliability, and problem solving.', turnPlan:['معرفی','سؤال درباره تجربه','مثال از یک مشکل','سؤال درباره انگیزه','پرسش متقابل','جمع‌بندی'], tags:['job','interview','work'] },
  { id:'work-meeting-disagreement', titleFa:'جلسه کاری و مخالفت محترمانه', titleEn:'Work meeting disagreement', category:'work', level:'B2', dialects:['american','iraqi','lebanese'], context:'دو همکار درباره اولویت یک کار اختلاف نظر دارند.', roles:[role('owner','مسئول پروژه','Project owner','باید نظر خود را با دلیل و داده توضیح دهد.',['شرح اولویت','پیشنهاد معیار تصمیم']),role('colleague','همکار','Colleague','نگران ریسک و زمان اجراست.',['بیان نگرانی','پیشنهاد جایگزین'])], objective:'بدون شخصی‌کردن اختلاف، یک تصمیم قابل اجرا بگیرید.', constraints:['به فرد حمله نکن؛ درباره مسئله صحبت کن.'], opening:'In a work meeting, you disagree with a colleague about which task should come first.', turnPlan:['بیان اختلاف','توضیح دلیل','شنیدن نگرانی','مقایسه گزینه‌ها','توافق بر معیار','تصمیم'], tags:['meeting','disagreement','negotiation'] },
  { id:'salary-negotiation', titleFa:'مذاکره حقوق', titleEn:'Salary negotiation', category:'negotiation', level:'C1', dialects:['american'], context:'نامزد شغلی درباره شرایط پیشنهادی سؤال می‌کند و می‌خواهد حرفه‌ای مذاکره کند.', roles:[role('candidate','نامزد','Candidate','می‌خواهد ارزش خود را توضیح دهد و درباره بسته پیشنهادی مذاکره کند.',['پرسیدن اجزای پیشنهاد','ارائه استدلال']),role('employer','کارفرما','Employer','باید محدوده و محدودیت‌های پیشنهاد را روشن کند.',['توضیح بسته','بررسی انعطاف'])], objective:'بدون تهدید یا ادعاهای غیرقابل اثبات، مذاکره حرفه‌ای انجام دهید.', constraints:['عدد واقعی حقوق یا شرکت واقعی وارد نکن.','درخواست‌ها را اولویت‌بندی کن.'], opening:'You received a job offer and want to discuss the compensation package professionally.', turnPlan:['تشکر و تأیید علاقه','پرسیدن ساختار بسته','ارائه ارزش','درخواست تغییر','بررسی گزینه‌های غیرحقوقی','جمع‌بندی'], tags:['salary','negotiation','career'] },
  { id:'customer-refund', titleFa:'مرجوعی کالا و بازپرداخت', titleEn:'Refund request', category:'service', level:'B1', dialects:['iraqi','lebanese','american'], context:'مشتری کالایی خریده که مشکل دارد و می‌خواهد راه‌حل منصفانه بگیرد.', roles:[role('customer','مشتری','Customer','می‌خواهد مشکل را توضیح دهد و طبق سیاست فروشگاه راه‌حل بگیرد.',['توضیح مشکل','پرسیدن گزینه‌های جبران']),role('agent','پشتیبان فروشگاه','Support agent','باید سیاست را توضیح دهد و در صورت امکان گزینه ارائه کند.',['بررسی سفارش','ارائه گزینه'])], objective:'مشکل را دقیق شرح دهید و به یک راه‌حل مشخص برسید.', constraints:['اطلاعات سفارش واقعی وارد نکن.'], opening:'A product you bought has a problem. Contact customer support and ask about a return or replacement.', turnPlan:['شرح خرید','شرح مشکل','پرسیدن سیاست','انتخاب گزینه','تأیید مراحل'], tags:['refund','customer-service','shopping'] },
  { id:'bank-transfer', titleFa:'بانک و انتقال وجه', titleEn:'Bank transfer help', category:'finance', level:'B1', dialects:['iraqi','lebanese','american'], context:'مشتری در مورد روش انتقال وجه و وضعیت تراکنش سؤال دارد.', roles:[role('client','مشتری بانک','Bank customer','می‌خواهد مراحل و وضعیت تراکنش را بفهمد.',['شرح مشکل','پرسیدن وضعیت و زمان']),role('banker','کارمند بانک','Bank staff','باید مراحل عمومی و اطلاعات لازم را توضیح دهد.',['توضیح روند','پرسیدن اطلاعات غیرحساس'])], objective:'روند را بفهمید بدون ارائه اطلاعات حساس واقعی.', constraints:['شماره کارت، حساب، رمز یا کد تأیید واقعی وارد نکن.'], opening:'Ask bank staff about a transfer that appears to be pending.', turnPlan:['شرح وضعیت','پرسیدن معنی pending','پرسیدن زمان تقریبی','پرسیدن اقدام بعدی','تأیید'], tags:['bank','money','security'] },
  { id:'phone-support', titleFa:'تماس با پشتیبانی اینترنت', titleEn:'Internet support call', category:'technology', level:'B1', dialects:['american','iraqi','lebanese'], context:'اینترنت قطع و وصل می‌شود و مشتری باید مشکل را مرحله‌به‌مرحله توضیح دهد.', roles:[role('user','مشتری','Customer','می‌خواهد مشکل را دقیق توصیف کند.',['توضیح علائم','انجام تست‌های ساده']),role('agent','کارشناس پشتیبانی','Support agent','باید سؤال‌های تشخیصی و مراحل رفع مشکل را ارائه کند.',['تشخیص اولیه','ارائه مراحل'])], objective:'مشکل فنی را بدون اصطلاحات مبهم توضیح دهید و مراحل را دنبال کنید.', constraints:['رمز یا اطلاعات ورود واقعی وارد نکن.'], opening:'Your internet connection keeps dropping. Call support and troubleshoot the issue.', turnPlan:['شرح مشکل','سؤال درباره زمان و دستگاه','اجرای تست','گزارش نتیجه','مرحله بعد'], tags:['internet','support','technology'] },
  { id:'software-bug-report', titleFa:'گزارش باگ نرم‌افزار', titleEn:'Software bug report', category:'technology', level:'B2', dialects:['american'], context:'کاربر یک خطای تکرارشونده دارد و باید گزارش قابل استفاده برای تیم فنی بدهد.', roles:[role('reporter','گزارش‌دهنده','Reporter','باید بازتولید، نتیجه مورد انتظار و واقعی را بگوید.',['شرح مراحل','ارائه شواهد غیرحساس']),role('engineer','مهندس نرم‌افزار','Engineer','می‌خواهد مشکل را قابل بازتولید کند.',['پرسیدن محیط','درخواست مراحل دقیق'])], objective:'یک bug report کوتاه اما قابل بازتولید بسازید.', constraints:['رمز، توکن و داده خصوصی واقعی وارد نکن.'], opening:'Report a reproducible software bug to an engineer.', turnPlan:['عنوان مشکل','مراحل بازتولید','نتیجه واقعی','نتیجه مورد انتظار','محیط اجرا','اولویت'], tags:['software','bug','technical'] },
  { id:'neighbor-noise', titleFa:'گفتگو با همسایه درباره سر و صدا', titleEn:'Noise complaint with a neighbor', category:'home', level:'B1', dialects:['iraqi','lebanese','american'], context:'سر و صدا در ساعات استراحت تکرار شده و باید محترمانه مطرح شود.', roles:[role('resident','همسایه شاکی','Resident','می‌خواهد آرامش برقرار شود بدون خراب‌شدن رابطه.',['توضیح زمان و اثر','درخواست مشخص']),role('neighbor','همسایه','Neighbor','ممکن است از مشکل آگاه نباشد و نیاز به توضیح دارد.',['شنیدن مشکل','پیشنهاد راه‌حل'])], objective:'درخواست خود را محترمانه و مشخص بیان کنید.', constraints:['تهدید یا توهین نکن.'], opening:'Talk to a neighbor about repeated noise during quiet hours.', turnPlan:['شروع دوستانه','شرح زمان و اثر','شنیدن دیدگاه','درخواست مشخص','توافق'], tags:['neighbors','home','politeness'] },
  { id:'landlord-repair', titleFa:'درخواست تعمیر از صاحبخانه', titleEn:'Requesting a rental repair', category:'home', level:'B1', dialects:['american','iraqi','lebanese'], context:'یک وسیله یا بخش خانه خراب شده و مستأجر باید درخواست تعمیر بدهد.', roles:[role('tenant','مستأجر','Tenant','می‌خواهد مشکل را مستند و پیگیری‌پذیر مطرح کند.',['شرح خرابی','درخواست زمان تعمیر']),role('landlord','صاحبخانه','Landlord','باید مشکل را بررسی و زمان‌بندی را مشخص کند.',['پرسیدن جزئیات','تعیین اقدام'])], objective:'مشکل را با زمان، اثر و درخواست مشخص گزارش کنید.', constraints:['قوانین محلی را فرض نکن؛ اگر لازم شد سؤال کن.'], opening:'Report a repair issue in a rental home and ask when it can be fixed.', turnPlan:['شرح خرابی','زمان شروع','اثر روی استفاده','درخواست تعمیر','زمان‌بندی','تأیید'], tags:['rent','repair','home'] },
  { id:'school-teacher', titleFa:'صحبت با معلم درباره پیشرفت', titleEn:'Talking to a teacher about progress', category:'education', level:'B1', dialects:['american','iraqi','lebanese'], context:'دانش‌آموز یا والد درباره عملکرد و برنامه بهبود سؤال دارد.', roles:[role('learner','یادگیرنده','Learner','می‌خواهد نقاط ضعف و قدم بعدی را بفهمد.',['پرسیدن ضعف‌ها','درخواست تمرین مشخص']),role('teacher','معلم','Teacher','باید بازخورد عملی و قابل اندازه‌گیری بدهد.',['شرح نقاط قوت','پیشنهاد تمرین'])], objective:'بازخورد را به اقدام عملی تبدیل کنید.', constraints:['نمره واقعی یا اطلاعات مدرسه واقعی وارد نکن.'], opening:'Ask a teacher what you should practice to improve your language performance.', turnPlan:['شرح هدف','پرسیدن نقاط ضعف','گرفتن مثال','درخواست تمرین','تعیین برنامه','تأیید'], tags:['school','feedback','learning'] },
  { id:'study-group', titleFa:'گروه مطالعه و تقسیم کار', titleEn:'Study group planning', category:'education', level:'B1', dialects:['american','iraqi','lebanese'], context:'چند نفر باید برای یک پروژه یا مطالعه گروهی وظایف را تقسیم کنند.', roles:[role('organizer','هماهنگ‌کننده','Organizer','می‌خواهد مسئولیت‌ها و زمان‌بندی روشن شود.',['پیشنهاد تقسیم کار','جمع‌بندی']),role('member','عضو گروه','Member','ظرفیت و ترجیح خود را توضیح می‌دهد.',['بیان توانایی','پذیرش مسئولیت'])], objective:'وظایف را منصفانه تقسیم و موعدها را روشن کنید.', constraints:['نام یا پروژه واقعی وارد نکن.'], opening:'Organize a small study project with another learner.', turnPlan:['تعریف هدف','فهرست کارها','تقسیم مسئولیت','زمان‌بندی','ریسک','تأیید'], tags:['study','planning','teamwork'] },
  { id:'social-introduction', titleFa:'آشنایی با فرد جدید', titleEn:'Meeting someone new', category:'social', level:'A1', dialects:['iraqi','lebanese','american'], context:'دو نفر در یک محیط عمومی با هم آشنا می‌شوند.', roles:[role('learner','زبان‌آموز','Learner','می‌خواهد مکالمه کوتاه و طبیعی داشته باشد.',['معرفی','پرسیدن سؤال ساده']),role('person','فرد جدید','New person','پاسخ می‌دهد و سؤال متقابل می‌پرسد.',['معرفی خود','ادامه گپ'])], objective:'یک گفتگوی کوتاه طبیعی بدون حفظ‌کردن متن انجام دهید.', constraints:['اطلاعات شخصی حساس نساز.'], opening:'You meet someone new at a public event. Start a friendly conversation.', turnPlan:['سلام','معرفی','سؤال درباره موقعیت','موضوع مشترک','خداحافظی'], tags:['small-talk','introduction','A1'] },
  { id:'family-visit', titleFa:'مهمانی خانوادگی و تعارف', titleEn:'Family visit and hospitality', category:'social', level:'A2', dialects:['iraqi','lebanese'], context:'مهمان وارد خانه می‌شود و گفتگو درباره پذیرایی و حال‌واحوال شکل می‌گیرد.', roles:[role('guest','مهمان','Guest','می‌خواهد مؤدبانه تشکر و درخواست کند.',['سلام و احوالپرسی','تشکر']),role('host','میزبان','Host','می‌خواهد مهمان راحت باشد.',['پیشنهاد پذیرایی','پرسیدن نیاز مهمان'])], objective:'تعارف و پاسخ طبیعی را تمرین کنید بدون ترجمه کلمه‌به‌کلمه.', constraints:['عبارت‌های اغراق‌آمیز را در صورت نیاز توضیح بده.'], opening:'Visit a family home and respond naturally to hospitality.', turnPlan:['ورود و سلام','احوالپرسی','پیشنهاد پذیرایی','پاسخ مودبانه','گفتگوی کوتاه','خداحافظی'], tags:['family','hospitality','culture'] },
  { id:'emergency-lost', titleFa:'گم‌شدن در شهر', titleEn:'Lost in the city', category:'emergency', level:'A2', dialects:['iraqi','lebanese','american'], context:'مسافر مسیر را گم کرده و باید کمک بگیرد.', roles:[role('traveler','مسافر','Traveler','می‌خواهد موقعیت و مقصد را توضیح دهد.',['درخواست کمک','پرسیدن مسیر']),role('local','فرد محلی','Local person','باید مسیر را ساده و مرحله‌ای توضیح دهد.',['پرسیدن مقصد','دادن راهنمایی'])], objective:'مقصد و مسیر را با جمله‌های کوتاه و قابل فهم بیان کنید.', constraints:['آدرس واقعی یا اطلاعات خصوصی وارد نکن.'], opening:'You are lost and ask a local person for directions.', turnPlan:['توجه گرفتن','شرح مقصد','پرسیدن مسیر','تکرار مسیر','تأیید'], tags:['directions','emergency','travel'] },
  { id:'emergency-police-report', titleFa:'گزارش یک مشکل به پلیس', titleEn:'Making a police report', category:'emergency', level:'B2', dialects:['american','iraqi','lebanese'], context:'فرد باید یک حادثه غیرخشونت‌آمیز را دقیق و بدون حدس گزارش کند.', roles:[role('reporter','گزارش‌دهنده','Reporter','باید زمان، مکان کلی و آنچه واقعاً دیده را بیان کند.',['شرح واقعیت','جداکردن مشاهده از حدس']),role('officer','افسر','Officer','باید اطلاعات ضروری و قابل بررسی را جمع کند.',['پرسش روشن','تأیید جزئیات'])], objective:'اطلاعات را دقیق، کوتاه و بدون حدس ارائه کنید.', constraints:['هیچ نام، شماره یا اطلاعات واقعی حساس وارد نکن.','اگر چیزی را نمی‌دانی بگو نمی‌دانم.'], opening:'Report a non-violent incident and distinguish what you saw from what you assume.', turnPlan:['شرح کوتاه','زمان و مکان کلی','مشاهده مستقیم','سؤال افسر','تأیید جزئیات','پایان'], tags:['police','report','safety'] },
  { id:'shopping-size', titleFa:'خرید لباس و تعویض سایز', titleEn:'Shopping for clothing and changing size', category:'service', level:'A2', dialects:['iraqi','lebanese','american'], context:'مشتری لباس می‌خواهد و درباره سایز، رنگ و تعویض سؤال دارد.', roles:[role('shopper','خریدار','Shopper','می‌خواهد سایز مناسب و سیاست تعویض را بفهمد.',['پرسیدن سایز','بررسی تعویض']),role('clerk','فروشنده','Clerk','باید گزینه‌ها و سیاست فروشگاه را توضیح دهد.',['پیشنهاد سایز','توضیح تعویض'])], objective:'نیاز خود را روشن بگویید و قبل از خرید سؤال‌های مهم را بپرسید.', constraints:['قیمت واقعی فروشگاه فرض نشود.'], opening:'Shop for clothing and ask about size, color, and exchange policy.', turnPlan:['توضیح نیاز','پرسیدن سایز','درخواست گزینه دیگر','پرسیدن تعویض','انتخاب'], tags:['shopping','clothes','service'] },
  { id:'market-price', titleFa:'بازار و چانه‌زنی محترمانه', titleEn:'Market price negotiation', category:'negotiation', level:'B1', dialects:['iraqi','lebanese'], context:'خریدار درباره قیمت کالا سؤال می‌کند و می‌خواهد تخفیف معقول بگیرد.', roles:[role('buyer','خریدار','Buyer','می‌خواهد قیمت و کیفیت را بفهمد و در صورت امکان تخفیف بگیرد.',['پرسیدن قیمت','درخواست تخفیف']),role('seller','فروشنده','Seller','باید قیمت و شرایط را توضیح دهد.',['شرح قیمت','پیشنهاد نهایی'])], objective:'چانه‌زنی را محترمانه و طبیعی انجام دهید.', constraints:['تخفیف قطعی یا قیمت واقعی را ادعا نکن.'], opening:'Ask about the price of an item and negotiate politely if appropriate.', turnPlan:['پرسیدن قیمت','پرسیدن کیفیت','درخواست تخفیف','پاسخ فروشنده','پیشنهاد متقابل','توافق یا خداحافظی'], tags:['market','price','negotiation'] },
  { id:'delivery-delay', titleFa:'پیگیری تأخیر سفارش', titleEn:'Late delivery follow-up', category:'service', level:'B1', dialects:['american','iraqi','lebanese'], context:'سفارش دیر شده و مشتری باید وضعیت را پیگیری کند.', roles:[role('customer','مشتری','Customer','می‌خواهد وضعیت و اقدام بعدی را بداند.',['شرح تأخیر','درخواست زمان‌بندی']),role('support','پشتیبان','Support agent','باید وضعیت را بررسی و گزینه بعدی را توضیح دهد.',['پرسیدن شناسه غیرحساس','ارائه اقدام'])], objective:'پیگیری مؤدبانه اما قاطع انجام دهید.', constraints:['شناسه سفارش واقعی وارد نکن.'], opening:'Follow up on a delivery that has not arrived when expected.', turnPlan:['شرح مشکل','پرسیدن وضعیت','درخواست اقدام','بررسی گزینه','تأیید'], tags:['delivery','support','shopping'] },
  { id:'doctor-symptom-description', titleFa:'توصیف دقیق علائم برای پزشک', titleEn:'Describing symptoms to a doctor', category:'health', level:'B2', dialects:['american','iraqi','lebanese'], context:'بیمار باید علائم را با زمان، شدت و عوامل مؤثر توصیف کند.', roles:[role('patient','بیمار','Patient','می‌خواهد علائم را دقیق توصیف کند.',['زمان شروع','شدت و عوامل']),role('doctor','پزشک','Doctor','برای فهم وضعیت سؤال‌های تکمیلی می‌پرسد.',['پرسش درباره علائم','توضیح قدم بعدی'])], objective:'توصیف منظم و قابل فهم ارائه دهید.', constraints:['این تمرین آموزشی است و تشخیص واقعی ارائه نمی‌کند.'], opening:'Describe a set of non-emergency symptoms clearly to a doctor.', turnPlan:['مشکل اصلی','زمان شروع','شدت','عوامل تشدید/تخفیف','سؤال پزشک','تأیید قدم بعدی'], tags:['doctor','symptoms','health'] },
  { id:'tech-device-setup', titleFa:'راه‌اندازی گوشی یا دستگاه جدید', titleEn:'Setting up a new device', category:'technology', level:'A2', dialects:['american','iraqi','lebanese'], context:'کاربر برای راه‌اندازی اولیه دستگاه سؤال دارد.', roles:[role('owner','کاربر دستگاه','Device owner','می‌خواهد مراحل را به زبان ساده دنبال کند.',['پرسیدن مرحله بعد','تأیید نتیجه']),role('helper','پشتیبان فنی','Technical helper','باید مراحل را کوتاه و مرحله‌ای توضیح دهد.',['ارائه مرحله','بررسی نتیجه'])], objective:'دستورالعمل مرحله‌ای را با سؤال و تأیید دنبال کنید.', constraints:['رمز یا کد واقعی وارد نکن.'], opening:'Ask for help setting up a new phone or device.', turnPlan:['شرح مرحله فعلی','پرسیدن مرحله بعد','انجام کار','گزارش نتیجه','ادامه'], tags:['device','setup','technology'] },
  { id:'appointment-reschedule', titleFa:'تغییر زمان قرار', titleEn:'Rescheduling an appointment', category:'daily', level:'A2', dialects:['american','iraqi','lebanese'], context:'فرد نمی‌تواند در زمان قبلی حاضر شود و باید زمان دیگری بگیرد.', roles:[role('caller','تماس‌گیرنده','Caller','می‌خواهد زمان را عوض کند و عذرخواهی کوتاهی داشته باشد.',['درخواست تغییر','انتخاب زمان جدید']),role('staff','کارمند','Staff member','باید زمان‌های ممکن را پیشنهاد کند.',['ارائه گزینه','تأیید زمان'])], objective:'قرار را بدون توضیح اضافی و با تأیید دقیق جابه‌جا کنید.', constraints:['تاریخ واقعی را وارد نکن؛ از تاریخ‌های فرضی استفاده کن.'], opening:'Call to reschedule an appointment you can no longer attend.', turnPlan:['سلام','درخواست تغییر','ارائه دلیل کوتاه','انتخاب زمان','تأیید'], tags:['appointment','phone','daily'] },
  { id:'public-transport', titleFa:'اتوبوس یا مترو و کارت سفر', titleEn:'Public transport help', category:'travel', level:'A2', dialects:['american','iraqi','lebanese'], context:'مسافر درباره مسیر، ایستگاه و روش پرداخت سؤال دارد.', roles:[role('passenger','مسافر','Passenger','می‌خواهد سریع‌ترین یا ساده‌ترین مسیر را بفهمد.',['پرسیدن مسیر','پرسیدن پرداخت']),role('staff','کارمند حمل‌ونقل','Transit staff','باید مسیر و قوانین عمومی را توضیح دهد.',['پیشنهاد مسیر','توضیح پرداخت'])], objective:'مقصد را مشخص کنید و مسیر را مرحله‌ای تکرار کنید.', constraints:['نام شهر واقعی لازم نیست؛ از مقصد نمونه استفاده کن.'], opening:'Ask transit staff how to reach a destination using public transport.', turnPlan:['مقصد','پرسیدن خط','پرسیدن ایستگاه','روش پرداخت','تأیید مسیر'], tags:['bus','metro','directions'] },
  { id:'event-registration', titleFa:'ثبت‌نام در رویداد', titleEn:'Event registration', category:'daily', level:'B1', dialects:['american','iraqi','lebanese'], context:'فرد می‌خواهد در یک کلاس یا رویداد ثبت‌نام کند و درباره شرایط سؤال دارد.', roles:[role('participant','شرکت‌کننده','Participant','می‌خواهد زمان، هزینه و شرایط را بداند.',['پرسیدن شرایط','انتخاب گزینه']),role('organizer','برگزارکننده','Organizer','باید اطلاعات ثبت‌نام را روشن کند.',['شرح شرایط','پاسخ به سؤال‌ها'])], objective:'اطلاعات لازم را جمع کنید و تصمیم بگیرید.', constraints:['قیمت و ظرفیت واقعی فرض نشود.'], opening:'Ask an event organizer about registration, schedule, and requirements.', turnPlan:['هدف','پرسیدن زمان','پرسیدن شرایط','پرسیدن هزینه در صورت وجود','ثبت‌نام یا تصمیم'], tags:['event','registration','daily'] },
  { id:'restaurant-complaint', titleFa:'اعتراض مؤدبانه درباره سفارش', titleEn:'Polite restaurant complaint', category:'service', level:'B1', dialects:['american','iraqi','lebanese'], context:'سفارش اشتباه یا ناقص آمده و مشتری باید بدون تنش آن را اصلاح کند.', roles:[role('customer','مشتری','Customer','می‌خواهد سفارش اصلاح شود.',['شرح اشتباه','درخواست مشخص']),role('server','پیشخدمت','Server','باید مشکل را بررسی و راه‌حل ارائه کند.',['تأیید مشکل','اصلاح سفارش'])], objective:'مشکل را روشن و بدون توهین مطرح کنید.', constraints:['تهدید یا تحقیر نکن.'], opening:'Your order is incorrect. Ask the server to fix it politely.', turnPlan:['اشاره به مشکل','توضیح دقیق','درخواست اصلاح','شنیدن پاسخ','تأیید'], tags:['restaurant','complaint','politeness'] },
  { id:'friend-plans', titleFa:'برنامه‌ریزی با دوست', titleEn:'Making plans with a friend', category:'social', level:'A2', dialects:['american','iraqi','lebanese'], context:'دو دوست برای یک فعالیت ساده برنامه‌ریزی می‌کنند.', roles:[role('planner','پیشنهاددهنده','Planner','می‌خواهد زمان و فعالیت مشخص شود.',['پیشنهاد','توافق روی زمان']),role('friend','دوست','Friend','ترجیح و محدودیت خود را می‌گوید.',['بیان ترجیح','پیشنهاد جایگزین'])], objective:'با پرسش و پیشنهاد به یک برنامه مشخص برسید.', constraints:['از اطلاعات واقعی شخصی استفاده نکن.'], opening:'Make a simple plan with a friend for a free afternoon.', turnPlan:['پیشنهاد','پرسیدن ترجیح','پیشنهاد جایگزین','انتخاب زمان','تأیید'], tags:['friends','plans','small-talk'] },
  { id:'work-email-followup', titleFa:'پیگیری حرفه‌ای یک ایمیل', titleEn:'Professional email follow-up', category:'work', level:'B2', dialects:['american'], context:'فرد باید بدون فشار بیش از حد، پاسخ یک درخواست کاری را پیگیری کند.', roles:[role('sender','فرستنده','Sender','می‌خواهد وضعیت درخواست را بفهمد.',['پیگیری کوتاه','درخواست زمان']),role('recipient','دریافت‌کننده','Recipient','ممکن است هنوز بررسی نکرده باشد یا نیاز به اطلاعات بیشتر داشته باشد.',['توضیح وضعیت','درخواست اطلاعات در صورت نیاز'])], objective:'پیگیری حرفه‌ای و کوتاه انجام دهید.', constraints:['اطلاعات واقعی شرکت یا فرد وارد نکن.'], opening:'Follow up on a professional request that has not received a response.', turnPlan:['یادآوری کوتاه','هدف پیام','پرسیدن وضعیت','ارائه کمک','تأیید قدم بعدی'], tags:['email','work','follow-up'] },
  { id:'negotiating-deadline', titleFa:'مذاکره برای مهلت تحویل', titleEn:'Negotiating a deadline', category:'negotiation', level:'B2', dialects:['american','iraqi','lebanese'], context:'فرد می‌بیند موعد فعلی واقع‌بینانه نیست و باید گزینه‌های جایگزین پیشنهاد کند.', roles:[role('owner','مجری کار','Owner','می‌خواهد کیفیت حفظ شود و موعد واقع‌بینانه شود.',['شرح ریسک','پیشنهاد زمان']),role('requester','درخواست‌کننده','Requester','به نتیجه و موعد نیاز دارد.',['شرح نیاز','بررسی مصالحه'])], objective:'با دلیل و گزینه مشخص درباره موعد مذاکره کنید.', constraints:['بهانه‌سازی نکن.'], opening:'Explain that a deadline is at risk and negotiate a realistic alternative.', turnPlan:['شرح وضعیت','اثر بر کیفیت','پیشنهاد گزینه','شنیدن نیاز طرف مقابل','مصالحه','تأیید'], tags:['deadline','negotiation','work'] },
  { id:'customer-subscription-cancel', titleFa:'لغو اشتراک', titleEn:'Canceling a subscription', category:'service', level:'B1', dialects:['american','iraqi','lebanese'], context:'کاربر می‌خواهد اشتراک را لغو کند و باید وضعیت تمدید و مراحل را بفهمد.', roles:[role('user','کاربر','User','می‌خواهد بدون هزینه ناخواسته اشتراک را لغو کند.',['پرسیدن تاریخ تمدید','تأیید لغو']),role('agent','پشتیبان','Support agent','باید سیاست و مراحل را توضیح دهد.',['توضیح مراحل','تأیید وضعیت'])], objective:'مراحل لغو و وضعیت تمدید را روشن کنید.', constraints:['شماره کارت یا اطلاعات حساب واقعی وارد نکن.'], opening:'Ask customer support to cancel a subscription and confirm whether it will renew.', turnPlan:['درخواست لغو','پرسیدن تمدید','توضیح گزینه‌ها','تأیید لغو','تأیید پایان'], tags:['subscription','support','billing'] },
  { id:'billing-dispute', titleFa:'پرسش درباره مبلغ صورتحساب', titleEn:'Questioning a bill', category:'finance', level:'B2', dialects:['american','iraqi','lebanese'], context:'مشتری مبلغی را متوجه نمی‌شود و می‌خواهد جزئیات را بررسی کند.', roles:[role('customer','مشتری','Customer','می‌خواهد منبع مبلغ را بفهمد.',['درخواست جزئیات','پرسیدن گزینه حل']),role('agent','کارشناس صورتحساب','Billing agent','باید ردیف‌های صورتحساب و روند اعتراض را توضیح دهد.',['شرح مبلغ','توضیح بررسی'])], objective:'به‌جای اتهام، درباره یک مبلغ مشخص سؤال کنید و مسیر بررسی را بفهمید.', constraints:['شماره حساب یا کارت واقعی وارد نکن.'], opening:'Ask billing support to explain an unfamiliar charge on a bill.', turnPlan:['اشاره به مبلغ','درخواست جزئیات','شنیدن توضیح','پرسیدن امکان بررسی','تأیید'], tags:['billing','money','support'] },
  { id:'language-exchange', titleFa:'تبادل زبان و اصلاح اشتباه', titleEn:'Language exchange correction', category:'education', level:'B1', dialects:['american','iraqi','lebanese'], context:'دو زبان‌آموز درباره یک موضوع روزمره حرف می‌زنند و یکی اشتباه طرف مقابل را اصلاح می‌کند.', roles:[role('learner','زبان‌آموز اول','Learner A','می‌خواهد آزادانه حرف بزند و بازخورد بگیرد.',['صحبت روان','پذیرش اصلاح']),role('partner','شریک زبان','Language partner','باید اصلاح کوتاه و طبیعی بدهد.',['اصلاح خطای مهم','ادامه مکالمه'])], objective:'اصلاح را بدون قطع جریان مکالمه انجام دهید و دوباره استفاده کنید.', constraints:['همه خطاها را اصلاح نکن؛ فقط موارد مفید را انتخاب کن.'], opening:'Have a natural conversation and correct only the most useful language mistakes.', turnPlan:['موضوع انتخابی','مکالمه آزاد','اصلاح یک خطای مهم','تکرار درست','ادامه بحث','جمع‌بندی'], tags:['language-exchange','feedback','learning'] },
  { id:'presentation-qna', titleFa:'ارائه و پرسش‌وپاسخ', titleEn:'Presentation Q&A', category:'work', level:'C1', dialects:['american'], context:'پس از یک ارائه، شنونده سؤال چالشی می‌پرسد.', roles:[role('presenter','ارائه‌دهنده','Presenter','باید پاسخ ساختاریافته و کوتاه بدهد.',['پاسخ مستقیم','بیان محدودیت']),role('audience','شنونده','Audience member','می‌خواهد یک سؤال دقیق و مرتبط بپرسد.',['پرسش روشن','پیگیری پاسخ'])], objective:'پاسخ را مستقیم، با دلیل و در صورت نیاز با محدودیت بیان کنید.', constraints:['ادعای داده یا منبع ساختگی نکن.'], opening:'Answer a challenging but fair question after a short professional presentation.', turnPlan:['سؤال','پاسخ مستقیم','دلیل','محدودیت','پیشنهاد قدم بعدی'], tags:['presentation','public-speaking','C1'] },
  { id:'apartment-viewing', titleFa:'بازدید خانه و سؤال‌های اجاره', titleEn:'Apartment viewing', category:'home', level:'B1', dialects:['american','iraqi','lebanese'], context:'فرد خانه‌ای را می‌بیند و درباره شرایط، تعمیرات و قوانین سؤال دارد.', roles:[role('viewer','متقاضی اجاره','Viewer','می‌خواهد شرایط واقعی خانه را بفهمد.',['پرسیدن امکانات','پرسیدن هزینه‌های جانبی']),role('agent','مشاور املاک','Agent','باید اطلاعات ملک را روشن کند و سؤال‌های دقیق را پاسخ دهد.',['شرح ملک','توضیح شرایط'])], objective:'قبل از تصمیم، سؤال‌های مهم و قابل بررسی را بپرسید.', constraints:['قوانین محلی یا هزینه واقعی را حدس نزن.'], opening:'View an apartment and ask practical questions before deciding.', turnPlan:['شرح نیاز','پرسیدن شرایط','بررسی مشکل','پرسیدن هزینه‌های جانبی','قدم بعدی'], tags:['apartment','rent','housing'] },
  { id:'community-volunteer', titleFa:'ثبت‌نام برای کار داوطلبانه', titleEn:'Volunteer registration', category:'social', level:'B1', dialects:['american','iraqi','lebanese'], context:'فرد می‌خواهد در یک فعالیت داوطلبانه مشارکت کند و درباره نقش‌ها سؤال دارد.', roles:[role('volunteer','داوطلب','Volunteer','می‌خواهد بداند چه کاری، چه زمانی و با چه مهارتی لازم است.',['شرح توانایی','انتخاب نقش']),role('coordinator','هماهنگ‌کننده','Coordinator','باید نیاز پروژه و وظایف را توضیح دهد.',['شرح وظیفه','هماهنگی زمان'])], objective:'نقش مناسب را انتخاب و مسئولیت را تأیید کنید.', constraints:['سازمان واقعی یا اطلاعات تماس واقعی لازم نیست.'], opening:'Ask how you can volunteer for a community activity.', turnPlan:['بیان علاقه','پرسیدن نیاز','شرح توانایی','انتخاب نقش','زمان‌بندی','تأیید'], tags:['volunteer','community','social'] },
  ...EVERYDAY_SCENARIOS,
];

export const SCENARIO_CATEGORIES: Array<{id: ScenarioCategory; labelFa:string}> = [
  {id:'travel',labelFa:'سفر و رفت‌وآمد'},{id:'work',labelFa:'کار و حرفه'},{id:'service',labelFa:'خدمات و خرید'},{id:'health',labelFa:'سلامت'},{id:'social',labelFa:'اجتماعی و خانواده'},{id:'education',labelFa:'تحصیل و یادگیری'},{id:'home',labelFa:'خانه و زندگی'},{id:'finance',labelFa:'مالی و بانکی'},{id:'technology',labelFa:'فناوری'},{id:'negotiation',labelFa:'مذاکره'},{id:'emergency',labelFa:'موقعیت حساس'},{id:'daily',labelFa:'روزمره'}
];

export function scenarioPrompt(s: Scenario, dialect: string): string {
  const roleA=s.roles[0]; const roleB=s.roles[1];
  return `SCENARIO MODE. You are the other role in a realistic role-play. Target dialect: ${dialect}. Scenario: ${s.titleEn}. Context: ${s.context}. Learner role: ${roleA.titleEn} — ${roleA.perspective}. Your role: ${roleB.titleEn} — ${roleB.perspective}. Objective: ${s.objective}. Constraints: ${s.constraints.join(' | ')}. Turn plan: ${s.turnPlan.join(' → ')}. Speak naturally, react to what the learner actually says, do not invent personal data, and do not force the learner through the plan if they take a different reasonable path. If a factual detail is unknown, say so or ask. Correct only important language mistakes briefly in Persian after the role-play turn when useful.`;
}
