import type { Scenario, ScenarioCategory, ScenarioRole } from './services/scenarioLibrary';

const role = (id:string,titleFa:string,titleEn:string,perspective:string,goals:string[]):ScenarioRole => ({id,titleFa,titleEn,perspective,goals});
const make = (x:{id:string;titleFa:string;titleEn:string;category:ScenarioCategory;level:Scenario['level'];context:string;objective:string;opening:string;tags:string[];roles?:[ScenarioRole,ScenarioRole];turnPlan?:string[];constraints?:string[]}):Scenario => ({
  id:x.id,titleFa:x.titleFa,titleEn:x.titleEn,category:x.category,level:x.level,dialects:['iraqi','lebanese','american'],context:x.context,
  roles:x.roles ?? [role('learner','یادگیرنده','Learner','می‌خواهد موقعیت را طبیعی و روشن مدیریت کند.',['بیان نیاز','گرفتن پاسخ']),role('partner','طرف مقابل','Conversation partner','باید طبیعی پاسخ دهد و اطلاعات لازم را روشن کند.',['پاسخ طبیعی','پیشبرد گفتگو'])],
  objective:x.objective,constraints:x.constraints ?? ['اطلاعات واقعی یا شخصی را فرض نکن.','اگر جزئیات لازم نامشخص است سؤال روشن بپرس.'],opening:x.opening,turnPlan:x.turnPlan ?? ['شروع گفتگو','توضیح نیاز','پرسش و پاسخ','انتخاب راه‌حل','تأیید نهایی'],tags:x.tags
});

export const EVERYDAY_SCENARIOS: Scenario[] = [
  make({id:'daily-coffee-order',titleFa:'سفارش قهوه روزانه',titleEn:'Ordering coffee',category:'daily',level:'A1',context:'فرد در کافه نوشیدنی ساده‌ای سفارش می‌دهد.',objective:'سفارش را واضح بدهید و یک تغییر ساده در سفارش مطرح کنید.',opening:'Order a coffee and ask for one simple change.',tags:['coffee','daily','ordering']}),
  make({id:'daily-grocery-question',titleFa:'پرسیدن جای یک کالا در فروشگاه',titleEn:'Finding an item in a store',category:'service',level:'A1',context:'مشتری دنبال یک کالای روزمره است.',objective:'محل کالا را بپرسید و پاسخ را تأیید کنید.',opening:'Ask a store employee where to find an everyday item.',tags:['shopping','store','directions']}),
  make({id:'daily-bus-card',titleFa:'خرید یا شارژ کارت اتوبوس',titleEn:'Getting a transit card',category:'travel',level:'A2',context:'مسافر درباره کارت حمل‌ونقل عمومی سؤال دارد.',objective:'نوع کارت، روش استفاده و مرحله بعد را بفهمید.',opening:'Ask how to get and use a local transit card.',tags:['bus','transport','city']}),
  make({id:'daily-package-pickup',titleFa:'تحویل گرفتن بسته',titleEn:'Picking up a package',category:'service',level:'A2',context:'فرد برای تحویل یک بسته به مرکز خدمات مراجعه می‌کند.',objective:'بسته را پیدا کنید و اطلاعات لازم برای تحویل را بپرسید.',opening:'Pick up a package and ask what is needed to receive it.',tags:['package','service','pickup']}),
  make({id:'daily-laundry',titleFa:'تحویل لباس به خشکشویی',titleEn:'Dropping off laundry',category:'daily',level:'A2',context:'مشتری درباره زمان آماده‌شدن و قیمت خدمات سؤال دارد.',objective:'نوع خدمت و زمان تحویل را مشخص کنید.',opening:'Drop off clothes and ask when they will be ready.',tags:['laundry','service','time']}),
  make({id:'daily-haircut',titleFa:'توضیح مدل مو',titleEn:'Explaining a haircut',category:'service',level:'A2',context:'مشتری می‌خواهد مدل مو و طول موردنظرش را توضیح دهد.',objective:'مدل دلخواه را با عبارت‌های ساده توضیح دهید.',opening:'Explain the haircut you want and ask one question about the service.',tags:['haircut','appearance','service']}),
  make({id:'daily-gym-membership',titleFa:'پرسیدن درباره باشگاه',titleEn:'Asking about a gym membership',category:'daily',level:'A2',context:'فرد درباره ساعات، امکانات و نحوه ثبت‌نام باشگاه سؤال دارد.',objective:'اطلاعات اصلی را بگیرید و تصمیم بگیرید.',opening:'Ask about a gym membership, opening hours, and basic facilities.',tags:['gym','membership','daily']}),
  make({id:'daily-neighbor-noise',titleFa:'صحبت محترمانه با همسایه',titleEn:'Talking to a neighbor about noise',category:'home',level:'B1',context:'صدای مزاحم ایجاد شده و باید محترمانه درباره آن صحبت شود.',objective:'مشکل را بدون تنش توضیح دهید و یک راه‌حل پیشنهاد کنید.',opening:'Politely talk to a neighbor about repeated noise.',tags:['neighbor','home','politeness']}),
  make({id:'daily-house-repair',titleFa:'درخواست تعمیر کوچک خانه',titleEn:'Requesting a small home repair',category:'home',level:'B1',context:'یک وسیله یا بخش کوچک خانه نیاز به تعمیر دارد.',objective:'مشکل، فوریت و زمان مناسب تعمیر را روشن کنید.',opening:'Ask a landlord or service person to arrange a small repair.',tags:['repair','home','request']}),
  make({id:'daily-phone-plan',titleFa:'پرسیدن درباره بسته تلفن',titleEn:'Asking about a phone plan',category:'technology',level:'B1',context:'کاربر درباره حجم اینترنت و هزینه یک بسته تلفن سؤال دارد.',objective:'ویژگی‌های اصلی بسته را مقایسه و انتخاب کنید.',opening:'Ask a phone provider about data, calls, and the basic terms of a plan.',tags:['phone','data','technology']}),
  make({id:'daily-wifi-problem',titleFa:'گزارش مشکل وای‌فای',titleEn:'Reporting a Wi-Fi problem',category:'technology',level:'A2',context:'اتصال اینترنت خانه قطع یا کند شده است.',objective:'مشکل را توضیح دهید و مراحل بررسی را بپرسید.',opening:'Tell support that your Wi-Fi is slow and ask what to check.',tags:['wifi','support','technology']}),
  make({id:'daily-bank-hours',titleFa:'پرسیدن ساعات بانک',titleEn:'Asking bank opening hours',category:'finance',level:'A1',context:'مشتری می‌خواهد زمان مناسب مراجعه را بداند.',objective:'ساعات کاری و نیاز احتمالی به وقت قبلی را بپرسید.',opening:'Ask a bank when it is open and whether an appointment is needed.',tags:['bank','hours','daily']}),
  make({id:'daily-cash-withdrawal',titleFa:'پرسیدن درباره خودپرداز',titleEn:'Finding an ATM',category:'finance',level:'A1',context:'مسافر یا مشتری دنبال خودپرداز است.',objective:'مسیر خودپرداز را بپرسید و پاسخ را تأیید کنید.',opening:'Ask where the nearest ATM is.',tags:['atm','directions','finance']}),
  make({id:'daily-event-registration',titleFa:'ثبت‌نام یک رویداد',titleEn:'Registering for an event',category:'education',level:'A2',context:'فرد می‌خواهد برای یک کلاس یا رویداد ثبت‌نام کند.',objective:'زمان، شرایط و مرحله ثبت‌نام را بفهمید.',opening:'Ask how to register for a class or local event.',tags:['event','registration','education']}),
  make({id:'daily-small-talk-weather',titleFa:'گفتگوی کوتاه درباره هوا',titleEn:'Small talk about the weather',category:'social',level:'A1',context:'دو نفر برای شروع گفتگوی کوتاه درباره هوا صحبت می‌کنند.',objective:'گفتگو را طبیعی شروع و با یک سؤال ادامه دهید.',opening:'Start a short natural conversation about today’s weather.',tags:['small-talk','weather','social']}),
  make({id:'daily-weekend-plans',titleFa:'صحبت درباره برنامه آخر هفته',titleEn:'Weekend plans',category:'social',level:'A1',context:'دو نفر درباره برنامه آخر هفته سؤال می‌کنند.',objective:'یک برنامه پیشنهاد دهید و درباره ترجیح طرف مقابل سؤال کنید.',opening:'Talk casually about weekend plans and suggest one activity.',tags:['weekend','plans','social']}),
  make({id:'daily-return-exchange',titleFa:'تعویض یک کالا',titleEn:'Exchanging an item',category:'service',level:'B1',context:'مشتری می‌خواهد کالا را با اندازه یا مدل دیگری عوض کند.',objective:'دلیل تعویض و گزینه جایگزین را روشن کنید.',opening:'Ask a store to exchange an item for a different size or version.',tags:['shopping','exchange','service']}),
  make({id:'daily-delivery-delay',titleFa:'پیگیری تأخیر ارسال',titleEn:'Following up on a delivery delay',category:'service',level:'B1',context:'ارسال دیر شده و مشتری وضعیت آن را پیگیری می‌کند.',objective:'وضعیت ارسال و قدم بعدی را بدون تنش بپرسید.',opening:'Ask customer support about a delayed delivery.',tags:['delivery','support','follow-up']}),
  make({id:'daily-meetup-change',titleFa:'تغییر زمان قرار',titleEn:'Changing a meeting time',category:'social',level:'A2',context:'فرد نمی‌تواند در زمان قبلی حاضر شود و زمان دیگری پیشنهاد می‌دهد.',objective:'زمان جدید را پیشنهاد و تأیید کنید.',opening:'Tell a friend you need to change the meeting time and suggest another.',tags:['plans','change','social']}),
  make({id:'daily-apology-misunderstanding',titleFa:'رفع یک سوءتفاهم',titleEn:'Clearing up a misunderstanding',category:'social',level:'B1',context:'یک سوءتفاهم کوچک در گفتگو ایجاد شده است.',objective:'بدون سرزنش منظور خود را روشن کنید.',opening:'Clear up a small misunderstanding without blaming the other person.',tags:['misunderstanding','politeness','conversation']}),
];
