export type EverydaySentence = {
  id: string;
  lang: 'english' | 'arabic';
  dialect: string;
  text: string;
  translation: string;
  category: string;
  level: 'A1' | 'A2' | 'B1' | 'B2';
  transliteration?: string;
};

/** Curated, short, high-frequency sentences intended for daily conversation. */
export const EVERYDAY_SENTENCES: EverydaySentence[] = [
  ['en-001','english','آمریکایی','I’m on my way.','دارم میام.','daily','A1'],
  ['en-002','english','آمریکایی','Give me a minute.','یک دقیقه بهم وقت بده.','daily','A1'],
  ['en-003','english','آمریکایی','I’ll be right back.','الان برمی‌گردم.','daily','A1'],
  ['en-004','english','آمریکایی','Are you ready?','آماده‌ای؟','daily','A1'],
  ['en-005','english','آمریکایی','Not yet.','هنوز نه.','daily','A1'],
  ['en-006','english','آمریکایی','I’m almost ready.','تقریباً آماده‌ام.','daily','A1'],
  ['en-007','english','آمریکایی','What are you doing?','داری چیکار می‌کنی؟','daily','A1'],
  ['en-008','english','آمریکایی','What’s going on?','چه خبره؟','daily','A1'],
  ['en-009','english','آمریکایی','How did it go?','چطور پیش رفت؟','daily','A1'],
  ['en-010','english','آمریکایی','That sounds good.','خوبه / خوب به نظر میاد.','daily','A1'],
  ['en-011','english','آمریکایی','That works for me.','برای من خوبه.','daily','A2'],
  ['en-012','english','آمریکایی','No problem at all.','اصلاً مشکلی نیست.','daily','A1'],
  ['en-013','english','آمریکایی','Take your time.','عجله نکن.','daily','A1'],
  ['en-014','english','آمریکایی','Don’t worry about it.','نگرانش نباش.','daily','A1'],
  ['en-015','english','آمریکایی','I’ll check and let you know.','بررسی می‌کنم و بهت خبر می‌دم.','daily','A2'],
  ['en-016','english','آمریکایی','Can you send it again?','می‌تونی دوباره بفرستیش؟','technology','A1'],
  ['en-017','english','آمریکایی','I didn’t get the message.','پیامت به دستم نرسید.','technology','A1'],
  ['en-018','english','آمریکایی','My phone is about to die.','شارژ گوشیم داره تموم می‌شه.','technology','A2'],
  ['en-019','english','آمریکایی','The connection is bad.','اتصال بده.','technology','A1'],
  ['en-020','english','آمریکایی','Can you hear me?','صدای منو می‌شنوی؟','technology','A1'],
  ['en-021','english','آمریکایی','I can’t hear you clearly.','صدات رو واضح نمی‌شنوم.','technology','A1'],
  ['en-022','english','آمریکایی','Let me call you back.','بذار دوباره بهت زنگ بزنم.','phone','A2'],
  ['en-023','english','آمریکایی','I’m a little busy right now.','الان یک‌کم سرم شلوغه.','daily','A1'],
  ['en-024','english','آمریکایی','Can we talk later?','می‌تونیم بعداً صحبت کنیم؟','daily','A1'],
  ['en-025','english','آمریکایی','What time works for you?','چه ساعتی برات مناسبه؟','planning','A2'],
  ['en-026','english','آمریکایی','Where should we meet?','کجا همدیگه رو ببینیم؟','planning','A1'],
  ['en-027','english','آمریکایی','I’ll meet you there.','همون‌جا می‌بینمت.','planning','A1'],
  ['en-028','english','آمریکایی','I’m running late.','دارم دیر می‌رسم.','travel','A1'],
  ['en-029','english','آمریکایی','I’ll be there in ten minutes.','ده دقیقه دیگه می‌رسم.','travel','A1'],
  ['en-030','english','آمریکایی','Which way is the station?','ایستگاه کدوم طرفه؟','travel','A1'],
  ['en-031','english','آمریکایی','Is this seat taken?','این صندلی اشغال شده؟','travel','A1'],
  ['en-032','english','آمریکایی','Could you help me with this?','می‌شه توی این کمکم کنی؟','service','A1'],
  ['en-033','english','آمریکایی','How much does this cost?','این چقدر قیمت داره؟','shopping','A1'],
  ['en-034','english','آمریکایی','Do you have a smaller one?','مدل کوچیک‌ترش رو دارید؟','shopping','A1'],
  ['en-035','english','آمریکایی','I’m just looking, thanks.','فقط دارم نگاه می‌کنم، ممنون.','shopping','A1'],
  ['en-036','english','آمریکایی','Can I pay by card?','می‌تونم با کارت پرداخت کنم؟','shopping','A1'],
  ['en-037','english','آمریکایی','Could I get this to go?','می‌شه اینو بیرون‌بر بگیرم؟','food','A2'],
  ['en-038','english','آمریکایی','Could we have the bill, please?','لطفاً صورت‌حساب رو میارید؟','food','A1'],
  ['en-039','english','آمریکایی','I’d like some water, please.','لطفاً کمی آب می‌خوام.','food','A1'],
  ['en-040','english','آمریکایی','I’m not sure what to order.','مطمئن نیستم چی سفارش بدم.','food','A2'],
  ['en-041','english','آمریکایی','I don’t eat spicy food.','غذای تند نمی‌خورم.','food','A1'],
  ['en-042','english','آمریکایی','Could you make it less spicy?','می‌شه کم‌تر تندش کنید؟','food','A2'],
  ['en-043','english','آمریکایی','I need to make an appointment.','باید وقت بگیرم.','health','A2'],
  ['en-044','english','آمریکایی','I’m not feeling well today.','امروز حالم خوب نیست.','health','A1'],
  ['en-045','english','آمریکایی','It started yesterday.','از دیروز شروع شده.','health','A1'],
  ['en-046','english','آمریکایی','I have a question about this.','درباره این یک سؤال دارم.','service','A1'],
  ['en-047','english','آمریکایی','Could you explain that again?','می‌شه دوباره توضیح بدید؟','learning','A1'],
  ['en-048','english','آمریکایی','Please speak a little slower.','لطفاً کمی آهسته‌تر صحبت کنید.','learning','A1'],
  ['en-049','english','آمریکایی','How do you say this naturally?','این رو طبیعی چطور می‌گن؟','learning','A2'],
  ['en-050','english','آمریکایی','What does that mean in this context?','در این موقعیت یعنی چی؟','learning','B1'],
  ['en-051','english','آمریکایی','Can you give me an example?','می‌تونی یک مثال بزنی؟','learning','A1'],
  ['en-052','english','آمریکایی','Let me try again.','بذار دوباره امتحان کنم.','learning','A1'],
  ['en-053','english','آمریکایی','I made a mistake.','اشتباه کردم.','learning','A1'],
  ['en-054','english','آمریکایی','What would you recommend?','چی رو پیشنهاد می‌کنی؟','service','A2'],
  ['en-055','english','آمریکایی','I’ll think about it.','درباره‌اش فکر می‌کنم.','daily','A1'],
  ['en-056','english','آمریکایی','That makes sense.','منطقیه / متوجه شدم.','conversation','A2'],
  ['en-057','english','آمریکایی','I see what you mean.','می‌فهمم منظورت چیه.','conversation','B1'],
  ['en-058','english','آمریکایی','I’m not sure yet.','هنوز مطمئن نیستم.','conversation','A1'],
  ['en-059','english','آمریکایی','Let’s keep it simple.','بیایید ساده نگهش داریم.','conversation','A2'],
  ['en-060','english','آمریکایی','Thanks for letting me know.','ممنون که خبر دادی.','conversation','A2'],
  ['ar-001','arabic','عراقی','شلونك اليوم؟','امروز چطوری؟','daily','A1','shlonak il-yom'],
  ['ar-002','arabic','عراقی','وين رايح؟','کجا می‌ری؟','daily','A1','wein rayeh'],
  ['ar-003','arabic','عراقی','وين رايحة؟','کجا می‌ری؟','daily','A1','wein rayha'],
  ['ar-004','arabic','عراقی','شوكت توصل؟','کی می‌رسی؟','planning','A1','shwakit twasal'],
  ['ar-005','arabic','عراقی','دقيقة بس.','فقط یک دقیقه.','daily','A1','daqeeqa bas'],
  ['ar-006','arabic','عراقی','هسه جاي.','الان دارم میام.','daily','A1','hassa jay'],
  ['ar-007','arabic','عراقی','بعدني ما وصلت.','هنوز نرسیدم.','travel','A1','baadni ma wisalt'],
  ['ar-008','arabic','عراقی','لا تشيل هم.','نگران نباش.','conversation','A2','la tsheel hamm'],
  ['ar-009','arabic','عراقی','ماكو مشكلة.','مشکلی نیست.','conversation','A1','maku mushkila'],
  ['ar-010','arabic','عراقی','ممكن تساعدني؟','می‌تونی کمکم کنی؟','service','A1','mumkin tsaedni'],
  ['ar-011','arabic','عراقی','أريد هذا لو سمحت.','این را می‌خواهم لطفاً.','shopping','A1','areed hatha law samaht'],
  ['ar-012','arabic','عراقی','بكم هذا؟','این چنده؟','shopping','A1','bikam hatha'],
  ['ar-013','arabic','عراقی','عندكم شي أرخص؟','چیز ارزان‌تری دارید؟','shopping','A2','indkum shay arkhas'],
  ['ar-014','arabic','عراقی','الحساب لو سمحت.','صورتحساب لطفاً.','food','A1','al-hisab law samaht'],
  ['ar-015','arabic','عراقی','أريد مي.','آب می‌خواهم.','food','A1','areed may'],
  ['ar-016','arabic','عراقی','ما أريد حار.','غذای تند نمی‌خواهم.','food','A2','ma areed har'],
  ['ar-017','arabic','عراقی','ممكن أقل حار؟','می‌شود کم‌تر تند باشد؟','food','A2','mumkin aqall har'],
  ['ar-018','arabic','عراقی','عندي سؤال.','یک سؤال دارم.','learning','A1','indi sual'],
  ['ar-019','arabic','عراقی','عيدها مرة ثانية.','یک بار دیگر بگو.','learning','A1','eedha marra thaniya'],
  ['ar-020','arabic','عراقی','احچي شوي أبطأ.','کمی آهسته‌تر صحبت کن.','learning','A2','ihchi shway abta'],
  ['ar-021','arabic','عراقی','شنو يعني هذا؟','این یعنی چی؟','learning','A1','shinu yani hatha'],
  ['ar-022','arabic','عراقی','ما فهمت.','نفهمیدم.','learning','A1','ma fihimt'],
  ['ar-023','arabic','عراقی','فهمت عليك.','فهمیدم منظورت را.','conversation','A2','fihimt alayk'],
  ['ar-024','arabic','عراقی','خلينا نجرب مرة ثانية.','بیایید یک بار دیگر امتحان کنیم.','learning','A2','khallina njarrib marra thaniya'],
  ['ar-025','arabic','عراقی','أشوفك بعدين.','بعداً می‌بینمت.','social','A1','ashufak baaden'],
  ['ar-026','arabic','عراقی','دير بالك على نفسك.','مراقب خودت باش.','social','A1','deer balak ala nafsak'],
  ['ar-027','arabic','عراقی','شلون نروح لهناك؟','چطور بریم آنجا؟','travel','A2','shlon nrooh lhinak'],
  ['ar-028','arabic','عراقی','هذا الطريق صحيح؟','این مسیر درسته؟','travel','A1','hatha al-tareeq saheeh'],
  ['ar-029','arabic','عراقی','تگدر تتصل بي بعدين؟','می‌تونی بعداً بهم زنگ بزنی؟','phone','A2','tigdir titasil bi baaden'],
  ['ar-030','arabic','عراقی','البطارية خلصانة.','باتری تموم شده.','technology','A1','al-battariya khalisana'],
  ['ar-031','arabic','عراقی','النت بطيء اليوم.','اینترنت امروز کند است.','technology','A1','al-net batee al-yom'],
  ['ar-032','arabic','عراقی','أرسل لي العنوان.','آدرس را برایم بفرست.','technology','A1','arsil li al-unwan'],
  ['ar-033','arabic','عراقی','وين أقرب محطة؟','نزدیک‌ترین ایستگاه کجاست؟','travel','A2','wein aqrab mahatta'],
  ['ar-034','arabic','عراقی','عندي موعد باچر.','فردا وقت دارم.','health','A2','indi mawid bacher'],
  ['ar-035','arabic','عراقی','أريد أحجز موعد.','می‌خواهم وقت بگیرم.','health','A2','areed ahjiz mawid'],
  ['ar-036','arabic','عراقی','من البارحة تعبان.','از دیروز خسته/بدحال هستم.','health','A2','min al-barha taaban'],
  ['ar-037','arabic','عراقی','خليني أتأكد.','بگذار مطمئن شوم.','conversation','A2','khallini atakkad'],
  ['ar-038','arabic','عراقی','أعطيك خبر.','بهت خبر می‌دم.','conversation','A2','ateek khabar'],
  ['ar-039','arabic','عراقی','ما عندي وقت هسه.','الان وقت ندارم.','daily','A1','ma indi waqt hassa'],
  ['ar-040','arabic','عراقی','عندي وقت اليوم.','امروز وقت دارم.','daily','A1','indi waqt al-yom'],
  ['ar-041','arabic','عراقی','شنو الخطة؟','برنامه چیه؟','planning','A1','shinu al-khutta'],
  ['ar-042','arabic','عراقی','خلينا نحدد وقت.','بیایید یک زمان مشخص کنیم.','planning','A2','khallina nhaddid waqt'],
  ['ar-043','arabic','عراقی','هذا يناسبني.','این برای من مناسبه.','planning','A2','hatha yinasibni'],
  ['ar-044','arabic','عراقی','ما يناسبني هالوقت.','این زمان برای من مناسب نیست.','planning','A2','ma yinasibni hal-waqt'],
  ['ar-045','arabic','عراقی','ممكن نغيره؟','می‌توانیم عوضش کنیم؟','planning','A1','mumkin nghayyira'],
  ['ar-046','arabic','عراقی','شنو رأيك؟','نظرت چیه؟','conversation','A1','shinu rayak'],
  ['ar-047','arabic','عراقی','على كيفك.','هر طور راحتی.','conversation','A2','ala keefak'],
  ['ar-048','arabic','عراقی','تمام، اتفقنا.','باشه، توافق کردیم.','conversation','A1','tamam, ittafaqna'],
  ['ar-049','arabic','عراقی','ما أريد أستعجل.','نمی‌خواهم عجله کنم.','daily','A2','ma areed astaajil'],
  ['ar-050','arabic','عراقی','خلينا نخليها بسيطة.','بیایید ساده نگهش داریم.','conversation','A2','khallina nkhalliha baseeta'],
  ['ar-051','arabic','عراقی','تعبان اليوم شوي.','امروز کمی خسته‌ام.','daily','A1','taaban al-yom shway'],
  ['ar-052','arabic','عراقی','جوعان، نروح ناكل؟','گرسنه‌ام، بریم چیزی بخوریم؟','food','A1','jooan, nrooh nakul'],
  ['ar-053','arabic','عراقی','تريد قهوة؟','قهوه می‌خوای؟','food','A1','treed qahwa'],
  ['ar-054','arabic','عراقی','أريد قهوة بدون سكر.','قهوه بدون شکر می‌خواهم.','food','A1','areed qahwa bidun sukkar'],
  ['ar-055','arabic','عراقی','الجو حلو اليوم.','هوا امروز خوبه.','daily','A1','al-jaw hilw al-yom'],
  ['ar-056','arabic','عراقی','اليوم الجو حار.','امروز هوا گرمه.','daily','A1','al-yom al-jaw har'],
  ['ar-057','arabic','عراقی','باچر نشوفك.','فردا می‌بینمت.','social','A1','bacher nshufak'],
  ['ar-058','arabic','عراقی','الله وياك.','خدا نگهدارت.','social','A1','allah wayak'],
  ['ar-059','arabic','عراقی','يعطيك العافية.','خسته نباشی / خدا قوت.','social','A2','yaatik al-afiya'],
  ['ar-060','arabic','عراقی','تسلم، شكراً.','ممنون، دستت درد نکنه.','social','A1','tislam, shukran'],
].map(([id,lang,dialect,text,translation,category,level,transliteration]) => ({ id,lang,dialect,text,translation,category,level, ...(transliteration ? {transliteration} : {}) })) as EverydaySentence[];
