// RC1 content expansion (item 3 of the 2026-09 bug/feature report):
// more realistic scenarios + roles, covering gaps in the original library
// (deeper family, emergency, workplace-tech, and education coverage).
import type { Scenario, ScenarioCategory, ScenarioRole } from './services/scenarioLibrary';

const role = (id: string, titleFa: string, titleEn: string, perspective: string, goals: string[]): ScenarioRole => ({ id, titleFa, titleEn, perspective, goals });
const make = (x: { id: string; titleFa: string; titleEn: string; category: ScenarioCategory; level: Scenario['level']; context: string; objective: string; opening: string; tags: string[]; roles?: [ScenarioRole, ScenarioRole]; turnPlan?: string[]; constraints?: string[]; dialects?: Array<'iraqi' | 'lebanese' | 'american'> }): Scenario => ({
  id: x.id, titleFa: x.titleFa, titleEn: x.titleEn, category: x.category, level: x.level,
  dialects: x.dialects ?? ['iraqi', 'lebanese', 'american'], context: x.context,
  roles: x.roles ?? [role('learner', 'یادگیرنده', 'Learner', 'می‌خواهد موقعیت را طبیعی و روشن مدیریت کند.', ['بیان نیاز', 'گرفتن پاسخ']), role('partner', 'طرف مقابل', 'Conversation partner', 'باید طبیعی پاسخ دهد و اطلاعات لازم را روشن کند.', ['پاسخ طبیعی', 'پیشبرد گفتگو'])],
  objective: x.objective, constraints: x.constraints ?? ['اطلاعات واقعی یا شخصی را فرض نکن.', 'اگر جزئیات لازم نامشخص است سؤال روشن بپرس.'],
  opening: x.opening, turnPlan: x.turnPlan ?? ['شروع گفتگو', 'توضیح نیاز', 'پرسش و پاسخ', 'انتخاب راه‌حل', 'تأیید نهایی'], tags: x.tags,
});

export const SCENARIO_EXPANSION_V2: Scenario[] = [
  make({ id: 'family-childcare-handoff', titleFa: 'هماهنگی نگهداری از بچه با همسر/خانواده', titleEn: 'Coordinating childcare', category: 'home', level: 'B1', context: 'دو نفر از اعضای خانواده باید برنامه رفت‌وآمد و نگهداری از کودک را هماهنگ کنند.', objective: 'زمان‌بندی مشخص و قابل اجرا برای روز بعد بگیرید.', opening: 'Coordinate who picks up and watches the kids tomorrow.', tags: ['family', 'schedule', 'childcare'] }),
  make({ id: 'family-elderly-checkin', titleFa: 'احوالپرسی تلفنی با یکی از بزرگترها', titleEn: 'Checking in with an elderly relative', category: 'social', level: 'A2', context: 'فرد با تماس تلفنی از حال یکی از اعضای مسن خانواده باخبر می‌شود.', objective: 'احوالپرسی گرم و پرسیدن نیازهای ساده انجام دهید.', opening: 'Call an older relative to check in and ask if they need anything.', tags: ['family', 'phone', 'care'] }),
  make({ id: 'emergency-fire-report', titleFa: 'گزارش بوی دود/آتش‌سوزی کوچک', titleEn: 'Reporting a small fire/smoke smell', category: 'emergency', level: 'B1', context: 'فرد بوی دود مشکوک احساس می‌کند و باید سریع و دقیق کمک بخواهد.', objective: 'مکان، وضعیت فعلی و فوریت را در چند جمله کوتاه و واضح بیان کنید.', opening: 'You smell smoke in the building and need to alert someone quickly.', constraints: ['آدرس واقعی وارد نکن؛ از توصیف نمونه استفاده کن.', 'جملات کوتاه و فوری باشند، نه توضیح طولانی.'], tags: ['emergency', 'safety', 'urgent'] }),
  make({ id: 'emergency-first-aid-call', titleFa: 'درخواست کمک برای آسیب جزئی', titleEn: 'Calling for help after a minor injury', category: 'emergency', level: 'A2', context: 'یکی نزدیکان دچار آسیب جزئی شده و باید کمک خواسته شود.', objective: 'وضعیت را ساده و دقیق توصیف کنید و کمک بخواهید.', opening: 'A friend has a minor injury; call for help and describe what happened.', tags: ['emergency', 'health', 'help'] }),
  make({ id: 'tech-password-reset', titleFa: 'بازیابی رمز عبور حساب کاربری', titleEn: 'Resetting an account password', category: 'technology', level: 'A2', context: 'کاربر دسترسی به حساب را از دست داده و با پشتیبانی تماس می‌گیرد.', objective: 'مشکل ورود را توضیح دهید و مراحل بازیابی را دنبال کنید.', opening: 'You are locked out of an account. Ask support how to reset access.', constraints: ['رمز، کد تأیید یا اطلاعات ورود واقعی وارد نکن.'], tags: ['technology', 'account', 'support'] }),
  make({ id: 'tech-online-order-tracking', titleFa: 'پیگیری وضعیت سفارش آنلاین', titleEn: 'Tracking an online order', category: 'technology', level: 'A2', context: 'خریدار می‌خواهد بداند سفارش آنلاینش در چه مرحله‌ای است.', objective: 'وضعیت سفارش را بپرسید و در صورت نیاز اقدام بعدی را بخواهید.', opening: 'Ask an online store where your order currently is.', tags: ['ecommerce', 'tracking', 'support'] }),
  make({ id: 'tech-video-call-setup', titleFa: 'راه‌اندازی تماس تصویری با خانواده', titleEn: 'Setting up a video call', category: 'technology', level: 'A1', context: 'فرد می‌خواهد به یکی کمک کند اپ تماس تصویری را راه بیندازد.', objective: 'مراحل ساده را قدم‌به‌قدم توضیح دهید.', opening: 'Help someone set up a video call for the first time.', tags: ['video-call', 'technology', 'help'] }),
  make({ id: 'work-remote-schedule', titleFa: 'هماهنگی ساعت کاری دورکاری', titleEn: 'Coordinating a remote work schedule', category: 'work', level: 'B1', context: 'همکار می‌خواهد ساعات در دسترس‌بودن دورکاری را هماهنگ کند.', objective: 'ساعات مشترک کاری را پیدا و تأیید کنید.', opening: 'Coordinate overlapping working hours with a remote colleague.', tags: ['remote-work', 'schedule', 'work'] }),
  make({ id: 'work-onboarding-questions', titleFa: 'سؤال‌های روز اول کاری', titleEn: 'First-day onboarding questions', category: 'work', level: 'A2', context: 'کارمند جدید سؤال‌های عملی درباره روز اول کار دارد.', objective: 'اطلاعات ضروری روز اول را بپرسید.', opening: 'Ask a manager practical questions on your first day at a new job.', tags: ['onboarding', 'work', 'new-job'] }),
  make({ id: 'work-sick-leave-request', titleFa: 'اطلاع دادن مرخصی استعلاجی', titleEn: 'Requesting sick leave', category: 'work', level: 'A2', context: 'فرد باید به مدیر خبر دهد که امروز نمی‌تواند سر کار حاضر شود.', objective: 'خبر را کوتاه، حرفه‌ای و به‌موقع اعلام کنید.', opening: 'Let your manager know you cannot come to work today.', constraints: ['جزئیات پزشکی خصوصی وارد نکن؛ فقط اعلام کلی مرخصی کافی است.'], tags: ['sick-leave', 'work', 'communication'] }),
  make({ id: 'education-university-application', titleFa: 'پرسش درباره ثبت‌نام دانشگاه', titleEn: 'Asking about university enrollment', category: 'education', level: 'B1', context: 'داوطلب درباره مدارک و مهلت ثبت‌نام سؤال دارد.', objective: 'مدارک لازم و زمان‌بندی را روشن کنید.', opening: 'Ask a university admissions office about required documents and deadlines.', tags: ['university', 'enrollment', 'education'] }),
  make({ id: 'education-language-test-info', titleFa: 'پرسیدن درباره آزمون زبان', titleEn: 'Asking about a language proficiency test', category: 'education', level: 'B1', context: 'فرد می‌خواهد بداند برای کدام آزمون زبان ثبت‌نام کند.', objective: 'تفاوت گزینه‌ها و مرحله بعد را بفهمید.', opening: 'Ask about the differences between available language proficiency exams.', tags: ['language-test', 'education', 'planning'] }),
  make({ id: 'education-tutor-scheduling', titleFa: 'هماهنگی جلسه با معلم خصوصی', titleEn: 'Scheduling a tutoring session', category: 'education', level: 'A2', context: 'دانش‌آموز می‌خواهد یک جلسه تمرین با معلم خصوصی هماهنگ کند.', objective: 'زمان و موضوع جلسه را مشخص کنید.', opening: 'Arrange a tutoring session and say which topic you want to focus on.', tags: ['tutoring', 'education', 'scheduling'] }),
  make({ id: 'weather-trip-planning', titleFa: 'بررسی وضع هوا قبل از سفر', titleEn: 'Checking weather before a trip', category: 'daily', level: 'A1', context: 'فرد قبل از سفر درباره وضع هوای مقصد می‌پرسد.', objective: 'اطلاعات هوا را بپرسید و برای آن آماده شوید.', opening: 'Ask a friend who lives there what the weather is usually like.', tags: ['weather', 'travel', 'small-talk'] }),
  make({ id: 'social-condolences', titleFa: 'ابراز همدردی محترمانه', titleEn: 'Offering condolences respectfully', category: 'social', level: 'B1', context: 'فرد می‌خواهد به شکلی محترمانه و کوتاه همدردی خود را ابراز کند.', objective: 'با جملات کوتاه، صمیمی و محترمانه همدردی کنید.', opening: 'A friend shares sad news. Respond with a short, respectful, caring message.', constraints: ['جزئیات غم‌انگیز واقعی نساز؛ روی لحن و ادب تمرکز کن.'], tags: ['condolences', 'empathy', 'social'] }),
  make({ id: 'social-congratulations', titleFa: 'تبریک گفتن یک خبر خوب', titleEn: 'Congratulating good news', category: 'social', level: 'A1', context: 'دوستی خبر خوبی (کار جدید، فرزند، ازدواج) داده است.', objective: 'با گرمی و طبیعی تبریک بگویید و یک سؤال پیگیری بپرسید.', opening: 'A friend shares good news. Congratulate them naturally.', tags: ['congratulations', 'social', 'small-talk'] }),
  make({ id: 'finance-budgeting-chat', titleFa: 'گفتگو درباره بودجه ماهانه', titleEn: 'Talking about a monthly budget', category: 'finance', level: 'B1', context: 'دو نفر درباره تقسیم هزینه‌های مشترک صحبت می‌کنند.', objective: 'یک تقسیم منصفانه و روشن پیشنهاد و توافق کنید.', opening: 'Discuss splitting a shared monthly expense fairly.', constraints: ['مبلغ واقعی ادعا نکن؛ از عدد نمونه استفاده کن.'], tags: ['budget', 'money', 'roommates'] }),
  make({ id: 'travel-visa-questions', titleFa: 'پرسیدن درباره مدارک ویزا', titleEn: 'Asking about visa requirements', category: 'travel', level: 'B2', context: 'مسافر درباره مدارک لازم برای یک نوع ویزا سؤال دارد.', objective: 'فهرست مدارک و مراحل کلی را بفهمید.', opening: 'Ask a visa office what documents are generally required.', constraints: ['اطلاعات حقوقی قطعی ادعا نکن؛ فقط سؤال و شنیدن پاسخ عمومی.'], tags: ['visa', 'travel', 'documents'] }),
  make({ id: 'service-warranty-claim', titleFa: 'استفاده از گارانتی یک محصول', titleEn: 'Making a warranty claim', category: 'service', level: 'B1', context: 'محصولی زیر گارانتی خراب شده و مشتری پیگیری می‌کند.', objective: 'مشکل را توضیح دهید و روند گارانتی را بفهمید.', opening: 'Ask a shop how to use the warranty on a broken product.', tags: ['warranty', 'service', 'shopping'] }),
  make({ id: 'negotiation-roommate-rules', titleFa: 'توافق بر سر قوانین هم‌خانه‌ای', titleEn: 'Agreeing on roommate house rules', category: 'negotiation', level: 'B2', context: 'دو هم‌خانه باید درباره نظم، مهمان و سکوت شبانه توافق کنند.', objective: 'قوانین مشخص و قابل اجرا با احترام متقابل تعیین کنید.', opening: 'Agree on basic house rules with a new roommate.', tags: ['roommates', 'negotiation', 'home'] }),
];
