export type DialectId = 'iraqi'|'lebanese'|'gulf'|'saudi'|'egyptian'|'msa'|'american';
export type DialectProfile = {id:DialectId;labelFa:string;locale:string;family:string;notes:string;prompt:string;learningFocus:string[];guardrails:string[]};
export const DIALECT_PROFILES:DialectProfile[]=[
 {id:'iraqi',labelFa:'عربی عراقی',locale:'ar-IQ',family:'Arabic',notes:'گفتاری عراق؛ تمرکز بر واژگان و ساخت‌های روزمره عراقی.',prompt:'Use Iraqi Arabic for natural spoken examples. Avoid MSA unless requested.',learningFocus:['گفتار روزمره','واژگان کاربردی','شنیدار عراقی','تمایز از خلیجی/سعودی'],guardrails:['اگر شکل منطقه‌ای قطعی نیست آن را قطعی معرفی نکن','از جایگزین کردن MSA به‌جای گفتار عراقی خودداری کن']},
 {id:'lebanese',labelFa:'عربی لبنانی',locale:'ar-LB',family:'Levantine Arabic',notes:'گفتاری لبنان؛ طبیعی، روزمره و مناسب مکالمه.',prompt:'Use Lebanese Arabic for natural spoken examples. Avoid MSA unless requested.',learningFocus:['گفتگوی روزمره','شنیدار شامی','واژگان لبنان','تمایز از MSA و مصری'],guardrails:['گونه لبنانی را با شامی عمومی یکی فرض نکن مگر زمینه کافی باشد','در موارد منطقه‌ای عدم قطعیت را اعلام کن']},
 {id:'gulf',labelFa:'عربی خلیجی',locale:'ar-AE',family:'Gulf Arabic',notes:'گونه عمومی خلیجی؛ برای مقایسه با عراقی و سعودی.',prompt:'Use Gulf Arabic. Prefer everyday spoken vocabulary and clearly mark regional variants.',learningFocus:['واژگان خلیجی','شنیدار','گفتگوی روزمره','مقایسه با عراقی و سعودی'],guardrails:['خلیجی را یک گونه واحد فرض نکن','صورت‌های منطقه‌ای را با برچسب منطقه ارائه کن']},
 {id:'saudi',labelFa:'عربی سعودی',locale:'ar-SA',family:'Najdi/Hejaz-oriented',notes:'برای تمرین سعودی؛ در صورت ابهام منطقه را مشخص کن.',prompt:'Use Saudi Arabic and identify regional uncertainty instead of inventing a dialect form.',learningFocus:['گفتار سعودی','واژگان روزمره','شنیدار','تفکیک نجدی/حجازی در صورت امکان'],guardrails:['لهجه سعودی را بدون تعیین منطقه بیش از حد دقیق نکن','صورت ساختگی را به‌عنوان سعودی ارائه نکن']},
 {id:'egyptian',labelFa:'عربی مصری',locale:'ar-EG',family:'Egyptian Arabic',notes:'گونه گفتاری مصر؛ مناسب شنیدار و مکالمه.',prompt:'Use Egyptian Arabic for spoken examples. Avoid MSA unless requested.',learningFocus:['مکالمه مصری','شنیدار','واژگان پرتکرار','تمایز از شامی و MSA'],guardrails:['از تبدیل خودکار مصری به MSA خودداری کن','اگر اصطلاح منطقه‌ای است آن را برچسب‌گذاری کن']},
 {id:'msa',labelFa:'عربی معیار (MSA)',locale:'ar',family:'Modern Standard Arabic',notes:'رسمی، خبری و نوشتاری.',prompt:'Use Modern Standard Arabic. Clearly distinguish it from dialectal speech.',learningFocus:['خواندن و نوشتار رسمی','واژگان معیار','دستور زبان','تشخیص تفاوت با عامیانه'],guardrails:['MSA را لهجه محاوره‌ای معرفی نکن','برای گفتار عامیانه برچسب گونه محاوره‌ای بده']},
 {id:'american',labelFa:'انگلیسی آمریکایی',locale:'en-US',family:'English',notes:'American English؛ طبیعی و محاوره‌ای.',prompt:'Use natural American English and common US usage.',learningFocus:['گفتار طبیعی','واژگان آمریکایی','شنیدار','pronunciation'],guardrails:['کاربرد آمریکایی را با انگلیسی بریتانیایی مخلوط نکن مگر برای مقایسه','اصطلاح عامیانه را با برچسب informal ارائه کن']}
];
export function getDialectProfile(id:string){return DIALECT_PROFILES.find(x=>x.id===id)||DIALECT_PROFILES[0]!}
export function buildDialectPrompt(id:string){const p=getDialectProfile(id);return `Target language variety: ${p.labelFa} (${p.locale}). ${p.prompt} Learning focus: ${p.learningFocus.join('، ')}. Guardrails: ${p.guardrails.join('؛ ')}. Explain corrections in Persian when useful.`}
export function compareDialects(concept:string){return DIALECT_PROFILES.filter(x=>x.id!=='american').map(x=>({dialect:x.id,labelFa:x.labelFa,query:`${concept} — ${x.labelFa}`,locale:x.locale}))}
